name = "sunny"
version = "0.3.0"
gleam = ">= 0.32.0"

description = "A gleam Open-meteo API client to get weather forecasts."
licences = ["MIT"]
repository = { type = "github", user = "leo-210", repo = "sunny" }

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
gleam_http = ">= 3.6.0 and < 4.0.0"
efetch = ">= 2.0.1 and < 3.0.0"
birl = ">= 1.7.1 and < 2.0.0"
gleam_json = ">= 1.0.1 and < 2.0.0"

[dev-dependencies]
glacier = ">= 1.1.0 and < 2.0.0"

[documentation]
pages = [
  { title = "Getting started", path = "getting_started.html", source = "./docs/getting_started.md" },
  { title = "Examples", path = "examples.html", source = "./docs/examples.md" },
  { title = "Example : City informations", path = "examples/city_info.html", source = "./docs/examples/city_info.md" },
  { title = "Example : Current temperature", path = "examples/current_temperature.html", source = "./docs/examples/current_temperature.md" },
  { title = "Example : Hourly forecast", path = "examples/hourly_forecast.html", source = "./docs/examples/hourly_forecast.md" },
]
